[package]
name = "nyah-cranelift"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift = "0.86"
cranelift-module = "0.86"
cranelift-jit = "0.86"
cranelift-object = "0.86"

nyah-il = { path = "../../il" }
