name: Run unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build the project
        run: cargo build --verbose

      - name: Perform the unit tests
        run: cargo test --verbose
